workflows:
  my-workflow:
    environment:
      xcode: 13.4
    scripts:
      - name: say hello
        script: echo "Hello Codemagician!"
      - name: Cocoapods Install
        script: |
          set -e # exit on first failed command

          gem install cocoapods -v 1.11.2 --no-document
          pod _1.11.2_ setup
          pod _1.11.2_ repo update
          pod _1.11.2_ install
      - name: Xcodebuild for iOS Simulator
        script: xcodebuild -scheme "RiotSwiftUI" -configuration "Debug"  COMPILER_INDEX_STORE_ENABLE=NO  ONLY_ACTIVE_ARCH=NO  -arch x86_64 -quiet -workspace "Riot.xcworkspace"
